### ISSUE TITLE
CmsService: Invalid Sitemap.xml

### ISSUE THREAD

**Issue by Oliviergg** [Majes/CmsBundle#1]
In Sitemap.xml, the loc url is invalid. There is no mention of http or https.
Example :

``` xml
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
<loc>www.example.com/fr</loc>
<lastmod>2014-07-04</lastmod>
<changefreq>weekly</changefreq>
</url>
```

Google Webmaster Tools said the sitemap is invalid.

**Comment by ghost** [comment]
This has been fixed in commit (Fixin Sitemap lack of Http)[https://github.com/Majes/CmsBundle/commit/6f147c1e08f42745910248ea42041ef9312c47fb], and released in (v1.20.25)[https://github.com/Majes/CmsBundle/releases/tag/v1.20.25] of CmsBundle.

Cheers
